"""add robustness verdict and stressed curves

Revision ID: 0efebb5f285f
Revises: 002_add_series_json
Create Date: 2026-07-09 17:18:20.526987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efebb5f285f'
down_revision: Union[str, None] = '002_add_series_json'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robustness_results', sa.Column('stressed_equity_curves', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robustness_results', 'stressed_equity_curves')
    # ### end Alembic commands ###
